# Docker Compose Configuration

version: '3'
name: automated-smart-contract-tester
services:
  services:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        STAGING: ${STAGING}
        PORT: ${SERVICES_PORT}
    env_file:
      - .env
    ports:
      - ${SERVICES_PORT}:${SERVICES_PORT}
    depends_on:
      - runner
  runner:
    build:
      context: ./test-runner
      dockerfile: Dockerfile
      args:
        STAGING: ${STAGING}
        PORT: ${TESTRUNNER_PORT}
    env_file:
      - .env
    volumes:
      - ${DOCKER_SOCKET_PATH}:${DOCKER_SOCKET_PATH} # Mount the Docker socket from the host machine into the Docker container
    ports:
      - ${TESTRUNNER_PORT}:${TESTRUNNER_PORT} # Remove later; it should only be accessible via services!
