# Docker Compose Configuration

version: '3'
services:
  test-runner:
    build:
      context: ./test-runner
      dockerfile: Dockerfile
    environment:
      - PORT=${TESTRUNNER_PORT}
      - MONGO_DB_URI=${TESTRUNNER_MONGO_DB_URI}
      - DOCKER_SOCKET_PATH=${DOCKER_SOCKET_PATH} # The Docker socket on the host machine
    volumes:
      - ${DOCKER_SOCKET_PATH}:${DOCKER_SOCKET_PATH} # Mount the Docker socket from the host machine into the Docker container
    ports:
      - ${TESTRUNNER_PORT}:${TESTRUNNER_PORT} # Remove later; it should only be accessible via services (use depends-on)!
