# Docker Compose Configuration

version: "3"
name: ${APP_NAME}
services:
  # Service: services
  services:
    container_name: ${APP_NAME}-${SERVICES_SERVICE_NAME}
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        STAGING: ${STAGING}
        PORT: ${SERVICES_PORT}
    environment:
      APP_NAME: ${APP_NAME}
      SERVICE_NAME: ${SERVICES_SERVICE_NAME}
      PORT: ${SERVICES_PORT}
      MONGO_DB_URI: ${SERVICES_MONGO_DB_URI}
      TESTRUNNER_HOST: ${APP_NAME}-${TESTRUNNER_SERVICE_NAME}:${TESTRUNNER_PORT} # app name + service name
    networks:
      - runner-isolated-network
    ports:
      - ${SERVICES_PORT}:${SERVICES_PORT}
    depends_on:
      - runner
  # Service: test-runner
  runner:
    container_name: ${APP_NAME}-${TESTRUNNER_SERVICE_NAME}
    build:
      context: ./test-runner
      dockerfile: Dockerfile
      args:
        STAGING: ${STAGING}
        PORT: ${TESTRUNNER_PORT}
    environment:
      APP_NAME: ${APP_NAME}
      SERVICE_NAME: ${TESTRUNNER_SERVICE_NAME}
      PORT: ${TESTRUNNER_PORT}
      MONGO_DB_URI: ${TESTRUNNER_MONGO_DB_URI}
    networks:
      - runner-isolated-network
    volumes:
      - ${DOCKER_SOCKET_PATH}:${DOCKER_SOCKET_PATH} # Mount the Docker socket from the host machine into the Docker container
    ports:
      - ${TESTRUNNER_PORT}:${TESTRUNNER_PORT} # Remove later; it should only be accessible through runner-isolated-network!
networks:
  runner-isolated-network:
