# Docker Compose Configuration

version: "3"
name: automated-smart-contract-testing
services:
  # Service: services
  services:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        STAGING: ${STAGING}
        PORT: ${SERVICES_PORT}
    env_file:
      - .env
    environment:
      TESTRUNNER_CONTAINER_NAME: automated-smart-contract-testing-runner # app name + service name
    networks:
      - runner-isolated-network
    ports:
      - ${SERVICES_PORT}:${SERVICES_PORT}
    depends_on:
      - runner
  # Service: test-runner
  runner:
    build:
      context: ./test-runner
      dockerfile: Dockerfile
      args:
        STAGING: ${STAGING}
        PORT: ${TESTRUNNER_PORT}
    env_file:
      - .env
    networks:
      - runner-isolated-network
    volumes:
      - ${DOCKER_SOCKET_PATH}:${DOCKER_SOCKET_PATH} # Mount the Docker socket from the host machine into the Docker container
    ports:
      - ${TESTRUNNER_PORT}:${TESTRUNNER_PORT} # Remove later; it should only be accessible via 'services' through 'runner-isolated-network'!
networks:
  runner-isolated-network:
